export interface Author{
    id:number;
    nombre:string;
    apellido:string;
    pais:string;
    provincia:string;
    ciudad:string;
    biografia:string;
}

export const AUTHOR_DATA: Author[] = [
    {
     id:1,
    nombre:'Vanessa',
    apellido:'Llerena',
    pais:'Ecuador',
    provincia:'Tungurahua',
    ciudad:'Ambato',
    biografia:'Ninguna'
      },
      {
     id:2,
    nombre:'Juan',
    apellido:'Llerena',
    pais:'Ecuador',
    provincia:'Tungurahua',
    ciudad:'Pichincha',
    biografia:'Ninguna'
      },
      {
        id:3,
        nombre:'Pablo',
        apellido:'Perez',
        pais:'Ecuador',
        provincia:'Tungurahua',
        ciudad:'Banos',
        biografia:'Ninguna'
      },
      {
        id:4,
        nombre:'Daniela',
        apellido:'Sanchez',
        pais:'Ecuador',
        provincia:'Guayas',
        ciudad:'Guayaquil',
        biografia:'Ninguna'
      }
      ,
      {
        id:5,
      nombre:'Juan',
      apellido:'Perez',
      pais:'Ecuador',
      provincia:'Guayas',
      ciudad:'Guayaquil',
      biografia:'Ninguna'
      }
      ,{
        id:6,
        nombre:'Juan',
        apellido:'Montana',
        pais:'Ecuador',
        provincia:'Guayas',
        ciudad:'Guayaquil',
        biografia:'Ninguna'
      },
      {
        id:7,
      nombre:'Paula',
      apellido:'Villafuerte',
      pais:'Ecuador',
      provincia:'Guayas',
      ciudad:'Guayaquil',
      biografia:'Ninguna'
      },
      {
        id:8,
        nombre:'Paola',
        apellido:'Monar',
        pais:'Ecuador',
        provincia:'Azuay',
        ciudad:'Cuenca',
        biografia:'Ninguna'
      },

]